#define NEXCACHE_GIT_SHA1 "34383397"
#define NEXCACHE_GIT_DIRTY "    4728"
#define NEXCACHE_BUILD_ID "MacBookPro.wind3.hub-1786869737"
#include "version.h"
#define NEXCACHE_BUILD_ID_RAW SERVER_NAME NEXCACHE_VERSION NEXCACHE_BUILD_ID NEXCACHE_GIT_DIRTY NEXCACHE_GIT_SHA1
